routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\WatchlistController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('about', fn () => view('about'));

Route::prefix('auth')->group(function () {
    Route::prefix('signup')->group(function () {
        Route::get('', fn () => view('auth.signup'));
        Route::post('', [LoginController::class, 'signup']);
    });

    Route::prefix('login')->group(function () {
        Route::get('', fn () => view('auth.login'))->name('login');
        Route::post('', [LoginController::class, 'authenticate']);
    });

    Route::post('logout', [LoginController::class, 'logout']);
});

Route::middleware('auth')->group(function () {
    Route::get('/', [WatchlistController::class, 'index']);

    Route::controller(WatchlistController::class)->group(function () {
        Route::prefix('watchlist')->name('watchlist.')->group(function () {
            Route::post('', 'addToWatchList');
            Route::prefix('{id}')->group(function () {
                Route::get('', 'show')->name('show');
                Route::post('mark-watched', 'markAsWatched')->name('mark-watched');
                Route::post('mark-unwatched', 'markAsUnwatched')->name('mark-unwatched');
                Route::delete('', 'destroy')->name('destroy');
            });
        });
    });
});

resources/views/about.blade.php
@extends('base')

@section('content')
<p>Welcome to FlixTick!</p>
<p>FlixTick is a fun little side-project to solve the problem of keeping track of which movies to watch. Even though most streaming apps out there have this functionality, there are tonnes of streaming apps out there; this is one list for all of them!</p>
<p>Expect improvements and additional functionality over the next several months!</p>
<ul>
    <li>We use only the absolutely necessary cookies needed for this site to function.</li>
    <li>You can see the full source code of this project <a href="https://github.com/arjkb/flixtick" target="_blank" rel="noopener noreferrer">here.</a></li>
    <li>Licensed under GNU AGPL v3.0. Find a copy of this license <a href="https://github.com/arjkb/flixtick/blob/master/LICENSE" target="_blank" rel="noopener noreferrer">here.</a></li>
</ul>

<h5 class="mt-4">About the developer</h5>
<p>My name is Arjun, and I'm a software developer from India. Visit my occasionally-updated blog <a href="https://arjkb.gitlab.io/post/" target="_blank" rel="noopener noreferrer">here.</a></p>
@endsection

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>FlixTick</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body class="antialiased">
    <nav class="navbar navbar-expand-sm navbar-light bg-light mb-2">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url('/') }}">FlixTick</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <!-- TODO: convert nav links to its own component -->
                    <a class="nav-link @if(url()->current() === url('/')) active @endif" aria-current="page" href="{{ url('/') }}">Home</a>
                    <a class="nav-link @if(url()->current() === url('about')) active @endif" aria-current="page" href="{{ url('about') }}">About</a>
                    @if(auth()->check())
                    <form action="{{ url('auth/logout') }}" method="post">
                        @csrf
                        <button type="submit" class="btn btn-link">Sign Out</button>
                    </form>
                    <span class="navbar-text">Hello {{ auth()->user()->username }}</span>
                    @else
                    <a class="nav-link @if(url()->current() === url('auth/login')) active @endif" href="{{ url('auth/login') }}">Log In</a>
                    <a class="nav-link @if(url()->current() === url('auth/signup')) active @endif" href="{{ url('auth/signup') }}">Sign Up</a>
                    @endif
                </div>
            </div>

        </div>
    </nav>
    <div class="container">
        @if(session('flash'))
        <div class="alert alert-primary">
            {{ session('flash') }}
        </div>
        @endif

        @if(session('flash-success'))
        <div class="alert alert-success">
            {{ session('flash-success') }}
        </div>
        @endif

        @if(session('flash-warning'))
        <div class="alert alert-warning">
            {{ session('flash-warning') }}
        </div>
        @endif

        @if(session('flash-danger'))
        <div class="alert alert-danger">
            {{ session('flash-danger') }}
        </div>
        @endif

        @yield('content')
    </div>

    <!-- Bootstrap JS and Popper bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>

</html>

resources/views/home.blade.php
@extends('base')

@section('content')
<div>
    <dl class="row mt-5">
        <dt class="col-sm-3">Unseen count</dt>
        <dd class="col-sm-9">{{ count($unwatchedMovies) }}</dd>

        <dt class="col-sm-3">Seen count</dt>
        <dd class="col-sm-9">{{ count($watchedMovies) }}</dd>

        <dt class="col-sm-3">Total</dt>
        <dd class="col-sm-9">{{ count($unwatchedMovies) + count($watchedMovies) }}</dd>
    </dl>
</div>

<form class="row row-cols-lg-auto g-3 align-items-center mt-3" action="{{ url('watchlist') }}" method="post">
    @csrf
    <div class="col-12">
        <label class="visually-hidden" for="title">Title</label>
        <input class="form-control @error('title') is-invalid @enderror" type="text" name="title" id="title" placeholder="Movie title" aria-describedby="validationServerTitleFeedback" autofocus required>
        @error('title')
        <div id="validationServerTitleFeedback" class="invalid-feedback">{{ $message }}</div>
        @enderror
    </div>

    <div class="col-12">
        <button type="submit" class="btn btn-sm btn-outline-primary">Add movie to watchlist</button>
    </div>
</form>

@if(isset($unwatchedMovies) || isset($watchedMovies))
<table class="table table-hover mt-3">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col" class="d-none d-md-table-cell">Added On</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($unwatchedMovies as $watchlistitem)
        <tr>
            <th scope="row">{{ $loop->iteration }}</th>
            <td>
                <a href="{{ route('watchlist.show', ['id' => $watchlistitem->id]) }}">{{ $watchlistitem->movie->title }}</a>
            </td>
            <td class="d-none d-md-table-cell">{{ $watchlistitem->movie->created_at?->diffForHumans() }}</td>
            <td>
                <form action="{{ route('watchlist.mark-watched', ['id' => $watchlistitem->id]) }}" method="post" class="row row-cols-lg-auto g-3 align-items-center">
                    @csrf
                    <div class="col-12">
                        <button type="submit" class="btn btn-sm btn-outline-primary">Mark as watched</button>
                    </div>
                </form>
            </td>
        </tr>
        @endforeach

        @foreach($watchedMovies as $watchlistitem)
        <tr class="text-muted">
            <th scope="row">{{ $loop->iteration + count($unwatchedMovies) }}</th>
            <td>
                <a class="link-secondary" href="{{ route('watchlist.show', ['id' => $watchlistitem->id]) }}">{{ $watchlistitem->movie->title }}</a>
                <br><span class="text-muted"><small>Marked seen {{ $watchlistitem->marked_seen_at->diffForHumans() }}</small></span>
            </td>
            <td class="d-none d-md-table-cell">{{ $watchlistitem->movie->created_at?->diffForHumans() }}</td>
            <td>
                <form action="{{ route('watchlist.mark-unwatched', ['id' => $watchlistitem->id]) }}" method="post" class="row row-cols-lg-auto g-3 align-items-center">
                    @csrf
                    <div class="col-12">
                        <button type="submit" class="btn btn-sm btn-outline-warning">Mark as unwatched</button>
                    </div>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif
@endsection