routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\WatchlistController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('about', fn () => view('about'));

Route::prefix('auth')->group(function () {
    Route::prefix('signup')->group(function () {
        Route::get('', fn () => view('auth.signup'));
        Route::post('', [LoginController::class, 'signup']);
    });

    Route::prefix('login')->group(function () {
        Route::get('', fn () => view('auth.login'))->name('login');
        Route::post('', [LoginController::class, 'authenticate']);
    });

    Route::post('logout', [LoginController::class, 'logout']);
});

Route::middleware('auth')->group(function () {
    Route::get('/', [WatchlistController::class, 'index']);

    Route::controller(WatchlistController::class)->group(function () {
        Route::prefix('watchlist')->name('watchlist.')->group(function () {
            Route::post('', 'addToWatchList');
            Route::prefix('{id}')->group(function () {
                Route::get('', 'show')->name('show');
                Route::post('mark-watched', 'markAsWatched')->name('mark-watched');
                Route::post('mark-unwatched', 'markAsUnwatched')->name('mark-unwatched');
                Route::delete('', 'destroy')->name('destroy');
            });
        });
    });
});

app/Models/Watchlist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Watchlist extends Model
{
    use HasFactory;

    protected $casts = [
        'marked_seen_at' => 'datetime',
        'user_id' => 'integer',
    ];

    /**
     * Get the movie that owns this watchlist record.
     *
     * @return void
     */
    public function movie()
    {
        return $this->belongsTo(Movie::class);
    }
}

app/Http/Controllers/WatchlistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Watchlist;
use App\Utilities\WatchlistUtility;
use Illuminate\Http\Request;

class WatchlistController extends Controller
{
    private WatchlistUtility $watchlist;

    public function __construct()
    {
        $this->watchlist = new WatchlistUtility;
    }

    /**
     * Get the watchlist for the logged in user.
     *
     * @return void
     */
    public function index()
    {
        $unwatchedMovies = Watchlist::with('movie')
        ->where('user_id', auth()->user()->id)
            ->whereNull('marked_seen_at')
            ->get()
            ->sortBy('movie.title', SORT_NATURAL | SORT_FLAG_CASE);

        $watchedMovies = Watchlist::with('movie')
        ->where('user_id', auth()->user()->id)
            ->whereNotNull('marked_seen_at')
            ->get()
            ->sortBy('movie.title', SORT_NATURAL | SORT_FLAG_CASE);

        return view('home', compact('unwatchedMovies', 'watchedMovies'));
    }

    /**
     * Show a watchlist item.
     *
     * @param integer $watchlistId
     * @return void
     */
    public function show(int $watchlistId)
    {
        $watchlistItem = Watchlist::find($watchlistId);

        $this->authorize('view', $watchlistItem);

        return view('watchlist.show', compact('watchlistItem'));
    }

    /**
     * Remove a record from the watchlist of a user.
     *
     * @param integer $watchlistId
     * @return void
     */
    public function destroy(int $watchlistId)
    {
        $w = Watchlist::find($watchlistId);

        $this->authorize('update', $w);

        $w->delete();

        return redirect('/')->with('flash-danger', "'{$w->movie->title}' removed from your watchlist");
    }

    /**
     * Add a movie to watchlist of the user
     *
     * @param Request $request
     * @return void
     */
    public function addToWatchlist(Request $request)
    {
        $validated = $request->validate([
            'title' => 'required|string'
        ]);

        $title = $validated['title'];

        $watchlistItemId = $this->watchlist->addToWatchlist(auth()->user()->id, $title);

        if ($watchlistItemId) {
            $flashMessage = "'$title' added to your watchlist";
            $flashType = 'flash-success';
        } else {
            $flashMessage = "'$title' is already in your watchlist; not added again";
            $flashType = 'flash-warning';
        }

        return redirect('/')->with($flashType, $flashMessage);
    }

    /**
     * Mark a movie as watched
     *
     * @param integer $id
     * @return void
     */
    public function markAsWatched(Request $request, int $id)
    {
        $watchlistItem = Watchlist::find($id);

        $this->authorize('update', $watchlistItem);

        $this->watchlist->markAsWatched($watchlistItem);

        return back()->with('flash-success', "'{$watchlistItem->movie->title}' marked as watched");
    }

    /**
     * Mark a movie as unwatched.
     *
     * @param integer $id
     * @return void
     */
    public function markAsUnwatched(int $id)
    {
        $watchlistItem = Watchlist::find($id);

        $this->authorize('update', $watchlistItem);

        $this->watchlist->markAsUnwatched($watchlistItem);

        return back()->with('flash-warning', "'{$watchlistItem->movie->title}' marked as unwatched");
    }
}

resources/views/watchlist/show.blade.php
@extends('base')

@section('content')
<h1>{{ $watchlistItem->movie->title }}</h1>

<dl class="row mt-5">
    @isset($watchlistItem->marked_seen_at)
    <dt class="col-sm-3">Marked watched at</dt>
    <dd class="col-sm-9">{{ $watchlistItem->marked_seen_at->diffForHumans() }}, on {{ $watchlistItem->marked_seen_at }} UTC</dd>
    @endisset

    <dt class="col-sm-3">Created at</dt>
    <dd class="col-sm-9">{{ $watchlistItem->created_at->diffForHumans() }}, on {{ $watchlistItem->created_at }} UTC</dd>

    <dt class="col-sm-3">Updated at</dt>
    <dd class="col-sm-9">{{ $watchlistItem->updated_at->diffForHumans() }}, on {{ $watchlistItem->updated_at }} UTC</dd>

    <dt class="col-sm-3"></dt>
    <dd class="col-sm-9">
        @if(isset($watchlistItem->marked_seen_at))
        <form action="{{ route('watchlist.mark-unwatched', ['id' => $watchlistItem->id]) }}" method="post">
            @csrf
            <button type="submit" class="btn btm-sm btn-outline-warning">Mark <em>'{{ $watchlistItem->movie->title }}'</em> as unwatched</button>
        </form>
        @else
        <form action="{{ route('watchlist.mark-watched', ['id' => $watchlistItem->id]) }}" method="post">
            @csrf
            <button type="submit" class="btn btm-sm btn-outline-success">Mark <em>'{{ $watchlistItem->movie->title }}'</em> as watched</button>
        </form>
        @endif
    </dd>

    <dt class="col-sm-3"></dt>
    <dd class="col-sm-9">
        <form action="{{ route('watchlist.destroy', ['id' => $watchlistItem->id]) }}" method="post">
            @method('DELETE')
            @csrf
            <button type="submit" class="btn btm-sm btn-outline-danger">Remove <em>'{{ $watchlistItem->movie->title }}'</em> from watchlist</button>
        </form>
    </dd>
</dl>
@endsection